# Generated by Django 4.2.1 on 2023-08-05 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0002_repository_user_alter_repository_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='repositories.repository'),
        ),
    ]
