name: Bandit Security Scan

# on: [push, pull_request]

jobs:
  bandit:
    runs-on: ubuntu-latest
    name: Bandit Security Scan
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit
      - name: Run Bandit
        run: bandit -r .
