name: Run Tests

on: [push, pull_request]

jobs:
  # frontend-tests:
  #   name: Frontend Tests
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: 14

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Run frontend tests
  #       run: npm test

  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEBUG: ${{ secrets.DEBUG }}
      ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
      DATABASE_URL: postgres://myuser:mypassword@localhost:5432/mydb
      BROKER_URL: ${{ secrets.BROKER_URL }}
      RESULT_URL: ${{ secrets.RESULT_URL }}
      SOCIAL_AUTH_GITHUB_KEY: ${{ secrets.SOCIAL_AUTH_GITHUB_KEY }}
      SOCIAL_AUTH_GITHUB_SECRET: ${{ secrets.SOCIAL_AUTH_GITHUB_SECRET }}
      GITHUB_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run backend tests
        run: python manage.py test
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
          POSTGRES_DB: mydb
          POSTGRES_HOST: localhost
        ports:
          - 5432:5432
      
      redis:
        image: "redis:latest"

